#!/bin/bash
# TODO Add parameter for speed farnsworth delay (g)
# TODO Add some randomness to pitch around selected value

# Get one quote TODO add parameters for length
./parse_quotes.py > one_quote

# Wait a second before starting
sleep 1

# Send morse
cat one_quote | cw -e -m -g 28 -w 20 -t 680 -v 20

# Print quote
cat one_quote
